server {
    listen 443 ssl;
    http2 on;
    server_name choup.app;

    include /etc/nginx/snippets/tls.conf;
    include /etc/nginx/snippets/private-site.conf;

    # The navigation page is temporarily disabled.
    location / {
        return 404;
    }
}
